//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substance_Synonym
    {
        public System.Guid Id { get; set; }
        public System.Guid IdSubstance { get; set; }
        public System.Guid IdSynonym { get; set; }
    
        public virtual Synonym Synonym { get; set; }
    }
}
