//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substance
    {
        public System.Guid Id { get; set; }
        public string ProductName { get; set; }
        public string FormulaHill { get; set; }
        public string CAS { get; set; }
        public string CPCU { get; set; }
        public string UN { get; set; }
    }
}
