//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Synonym
    {
        public Synonym()
        {
            this.Substance_Synonym = new HashSet<Substance_Synonym>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Substance_Synonym> Substance_Synonym { get; set; }
    }
}
